version: "3.9"
services:
  bookstore-db:
    image: "mongo:latest"
    container_name: "bookstore-db-container"
    ports:
       - "27017:27017" #Expose this if you want to connect mongo-client(compass) from external sources(Web).
    networks:
      - my-network

  bookstore-api:
    image: "bookstore-api"
    build:
      context: ../
      dockerfile: Bookstore.Api/Dockerfile
    container_name: "bookstore-api-container"
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Bookstore_DockerCompose
    networks:
      - my-network
    depends_on:
      - jaeger
      - otel-collector 
 
  jaeger:
    image: jaegertracing/opentelemetry-all-in-one
    container_name: jaeger
    ports:
      - "13133:13133"
      - "16686:16686"
      - "4318:4317"
      - "14250" 
    restart: unless-stopped
    networks:
      - my-network
 
 # Add the OpenTelemetry Collector service
  otel-collector:
    image: otel/opentelemetry-collector:0.99.0
    container_name: otel-collector
    ports:
      - "127.0.0.1:4317:4317"
      - "127.0.0.1:55679:55679"
    networks:
      - my-network
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - "C:/Users/Joseph_A/source/repos/DockerInfra/config.yaml:/etc/otel-collector-config.yaml"
    restart: unless-stopped

networks:
  my-network:
    driver: bridge
    